// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiAJk-EOMngPk0xAPVsLX6jef8S6Yna7c',
    appId: '1:390174952980:web:377efa60152e872a39a101',
    messagingSenderId: '390174952980',
    projectId: 'piga-luku-customer-app',
    authDomain: 'piga-luku-customer-app.firebaseapp.com',
    storageBucket: 'piga-luku-customer-app.appspot.com',
    measurementId: 'G-QYRSCDR7CT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf_HJfR0rAT4cLWuCr7kD_vO1rRB2GI7w',
    appId: '1:390174952980:android:dbdb6e1e3b732b4339a101',
    messagingSenderId: '390174952980',
    projectId: 'piga-luku-customer-app',
    storageBucket: 'piga-luku-customer-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-IsLuLqYAyeowF-TZRDqyk2Rqi5qw_6o',
    appId: '1:390174952980:ios:af1a590a44ad55bc39a101',
    messagingSenderId: '390174952980',
    projectId: 'piga-luku-customer-app',
    storageBucket: 'piga-luku-customer-app.appspot.com',
    androidClientId: '390174952980-c10coujm1e24v80qvuk9lod1bd79l45k.apps.googleusercontent.com',
    iosClientId: '390174952980-2c1ms2f0s9to284dor9h348htgj6mqfq.apps.googleusercontent.com',
    iosBundleId: 'com.example.pigalukudelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-IsLuLqYAyeowF-TZRDqyk2Rqi5qw_6o',
    appId: '1:390174952980:ios:af1a590a44ad55bc39a101',
    messagingSenderId: '390174952980',
    projectId: 'piga-luku-customer-app',
    storageBucket: 'piga-luku-customer-app.appspot.com',
    androidClientId: '390174952980-c10coujm1e24v80qvuk9lod1bd79l45k.apps.googleusercontent.com',
    iosClientId: '390174952980-2c1ms2f0s9to284dor9h348htgj6mqfq.apps.googleusercontent.com',
    iosBundleId: 'com.example.pigalukudelivery',
  );
}
